name: Generate and Deploy Documentation

on:
  push:
    branches:
      - 44-documentation-hosting

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Generate documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with: 
          working-directory: 'docs/'
          doxyfile-path: 'Doxygen'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ${{github.workspace}}/docs/html